-- =====================================================================
-- 01_ddl_turismouq.sql
-- Proyecto Integrador TurismoUQ - Bases de Datos II (Univ. del Quindio)
-- Entrega 1 - Script DDL (tablas + restricciones)
-- ---------------------------------------------------------------------
-- 0. LIMPIEZA: permite re-ejecutar el script en un esquema ya usado.
-- ---------------------------------------------------------------------
BEGIN
  FOR t IN (SELECT column_value AS nombre
              FROM TABLE(sys.odcivarchar2list(
                     'RESENA','RESERVA_SERVICIO','PAGO','RESERVA_HABITACION',
                     'RESERVA','TARIFA','SERVICIO','HABITACION','USUARIO_SISTEMA',
                     'ROL','ALOJAMIENTO','CLIENTE','TEMPORADA',
                     'TIPO_ALOJAMIENTO','MUNICIPIO'))) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.nombre || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
    END;
  END LOOP;
END;
/

-- =====================================================================
-- 1. CATALOGOS BASE
-- =====================================================================

-- ---------------------------------------------------------------------
-- MUNICIPIO: los 12 municipios del Quindio.
-- ---------------------------------------------------------------------
CREATE TABLE municipio (
  id_municipio  NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  nombre        VARCHAR2(60)  NOT NULL,
  CONSTRAINT pk_municipio        PRIMARY KEY (id_municipio),
  CONSTRAINT uq_municipio_nombre UNIQUE (nombre)
);

-- ---------------------------------------------------------------------
-- TIPO_ALOJAMIENTO: finca cafetera, hotel, glamping, hostal, etc.
-- ---------------------------------------------------------------------
CREATE TABLE tipo_alojamiento (
  id_tipo  NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  nombre   VARCHAR2(40)  NOT NULL,
  CONSTRAINT pk_tipo_alojamiento        PRIMARY KEY (id_tipo),
  CONSTRAINT uq_tipo_alojamiento_nombre UNIQUE (nombre)
);

-- ---------------------------------------------------------------------
-- ROL: catalogo de roles de los usuarios internos de la plataforma.
-- ---------------------------------------------------------------------
CREATE TABLE rol (
  id_rol       NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  nombre       VARCHAR2(30)   NOT NULL,
  descripcion  VARCHAR2(200),
  CONSTRAINT pk_rol        PRIMARY KEY (id_rol),
  CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

-- ---------------------------------------------------------------------
-- TEMPORADA: rango de fechas con categoria alta/media/baja, por anio.
-- ---------------------------------------------------------------------
CREATE TABLE temporada (
  id_temporada  NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  nombre        VARCHAR2(80)  NOT NULL,
  categoria     VARCHAR2(10)  NOT NULL,
  fecha_inicio  DATE          NOT NULL,
  fecha_fin     DATE          NOT NULL,
  anio          NUMBER(4)     NOT NULL,
  CONSTRAINT pk_temporada           PRIMARY KEY (id_temporada),
  CONSTRAINT uq_temporada_nombre    UNIQUE (nombre),
  CONSTRAINT ck_temporada_categoria CHECK (categoria IN ('ALTA','MEDIA','BAJA')),
  CONSTRAINT ck_temporada_fechas    CHECK (fecha_fin >= fecha_inicio),
  CONSTRAINT ck_temporada_anio      CHECK (anio = EXTRACT(YEAR FROM fecha_inicio))
);

-- ---------------------------------------------------------------------
-- CLIENTE: huesped registrado en la plataforma.
-- ---------------------------------------------------------------------
CREATE TABLE cliente (
  id_cliente     NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  nombre         VARCHAR2(120)  NOT NULL,
  documento      VARCHAR2(20)   NOT NULL,
  correo         VARCHAR2(100)  NOT NULL,
  telefono       VARCHAR2(20),
  ciudad_origen  VARCHAR2(80)   NOT NULL,
  CONSTRAINT pk_cliente           PRIMARY KEY (id_cliente),
  CONSTRAINT uq_cliente_documento UNIQUE (documento),
  CONSTRAINT uq_cliente_correo    UNIQUE (correo),
  CONSTRAINT ck_cliente_correo    CHECK (correo LIKE '%_@_%._%')
);

-- =====================================================================
-- 2. OFERTA DE ALOJAMIENTO
-- =====================================================================

-- ---------------------------------------------------------------------
-- ALOJAMIENTO: establecimiento comercial de un municipio y un tipo.
-- ---------------------------------------------------------------------
CREATE TABLE alojamiento (
  id_alojamiento   NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  id_municipio     NUMBER         NOT NULL,
  id_tipo          NUMBER         NOT NULL,
  nombre_comercial VARCHAR2(120)  NOT NULL,
  direccion        VARCHAR2(200)  NOT NULL,
  estrellas        NUMBER(1)      NOT NULL,
  telefono         VARCHAR2(20),
  correo_contacto  VARCHAR2(100),
  CONSTRAINT pk_alojamiento          PRIMARY KEY (id_alojamiento),
  CONSTRAINT fk_alojamiento_municipio FOREIGN KEY (id_municipio)
                                      REFERENCES municipio (id_municipio),
  CONSTRAINT fk_alojamiento_tipo      FOREIGN KEY (id_tipo)
                                      REFERENCES tipo_alojamiento (id_tipo),
  CONSTRAINT uq_alojamiento_nombre    UNIQUE (id_municipio, nombre_comercial),
  CONSTRAINT ck_alojamiento_estrellas CHECK (estrellas BETWEEN 1 AND 5),
  CONSTRAINT ck_alojamiento_correo    CHECK (correo_contacto IS NULL
                                             OR correo_contacto LIKE '%_@_%._%')
);

-- ---------------------------------------------------------------------
-- HABITACION: unidad reservable de un alojamiento.
-- ---------------------------------------------------------------------
CREATE TABLE habitacion (
  id_habitacion   NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  id_alojamiento  NUMBER         NOT NULL,
  numero          VARCHAR2(10)   NOT NULL,
  capacidad_max   NUMBER(2)      NOT NULL,
  tipo            VARCHAR2(15)   NOT NULL,
  descripcion     VARCHAR2(300),
  CONSTRAINT pk_habitacion            PRIMARY KEY (id_habitacion),
  CONSTRAINT fk_habitacion_alojamiento FOREIGN KEY (id_alojamiento)
                                       REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uq_habitacion_numero      UNIQUE (id_alojamiento, numero),
  CONSTRAINT ck_habitacion_capacidad   CHECK (capacidad_max > 0),
  CONSTRAINT ck_habitacion_tipo        CHECK (tipo IN ('SENCILLA','DOBLE','SUITE','CABANA'))
);

-- ---------------------------------------------------------------------
-- TARIFA: precio por noche de una habitacion en una temporada.
-- Resuelve la relacion N:M HABITACION-TEMPORADA. Una tarifa por cada
-- combinacion habitacion x temporada. (Decision de diseno 2.)
-- ---------------------------------------------------------------------
CREATE TABLE tarifa (
  id_tarifa      NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  id_habitacion  NUMBER         NOT NULL,
  id_temporada   NUMBER         NOT NULL,
  valor_noche    NUMBER(12,2)   NOT NULL,
  CONSTRAINT pk_tarifa            PRIMARY KEY (id_tarifa),
  CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion)
                                  REFERENCES habitacion (id_habitacion),
  CONSTRAINT fk_tarifa_temporada  FOREIGN KEY (id_temporada)
                                  REFERENCES temporada (id_temporada),
  CONSTRAINT uq_tarifa_hab_temp   UNIQUE (id_habitacion, id_temporada),
  CONSTRAINT ck_tarifa_valor      CHECK (valor_noche > 0)
);

-- ---------------------------------------------------------------------
-- SERVICIO: servicio complementario que pertenece a UN alojamiento.
-- ---------------------------------------------------------------------
CREATE TABLE servicio (
  id_servicio     NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  id_alojamiento  NUMBER         NOT NULL,
  nombre          VARCHAR2(80)   NOT NULL,
  descripcion     VARCHAR2(300),
  precio          NUMBER(12,2)   NOT NULL,
  CONSTRAINT pk_servicio             PRIMARY KEY (id_servicio),
  CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento)
                                     REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uq_servicio_nombre      UNIQUE (id_alojamiento, nombre),
  CONSTRAINT ck_servicio_precio      CHECK (precio >= 0)
);

-- =====================================================================
-- 3. RESERVAS, PAGOS Y RESENAS
-- =====================================================================

-- ---------------------------------------------------------------------
-- RESERVA: cabecera de la reserva (cliente, alojamiento, rango general).
-- ---------------------------------------------------------------------
CREATE TABLE reserva (
  id_reserva         NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  id_cliente         NUMBER        NOT NULL,
  id_alojamiento     NUMBER        NOT NULL,
  fecha_creacion     DATE          DEFAULT SYSDATE NOT NULL,
  fecha_checkin      DATE          NOT NULL,
  fecha_checkout     DATE          NOT NULL,
  estado             VARCHAR2(12)  DEFAULT 'PENDIENTE' NOT NULL,
  fecha_cancelacion  DATE,
  CONSTRAINT pk_reserva             PRIMARY KEY (id_reserva),
  CONSTRAINT fk_reserva_cliente     FOREIGN KEY (id_cliente)
                                    REFERENCES cliente (id_cliente),
  CONSTRAINT fk_reserva_alojamiento FOREIGN KEY (id_alojamiento)
                                    REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT ck_reserva_estado      CHECK (estado IN ('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA')),
  CONSTRAINT ck_reserva_fechas      CHECK (fecha_checkout > fecha_checkin),
  CONSTRAINT ck_reserva_creacion    CHECK (TRUNC(fecha_creacion) <= fecha_checkin),
  CONSTRAINT ck_reserva_cancelacion CHECK (
        (estado =  'CANCELADA' AND fecha_cancelacion IS NOT NULL)
     OR (estado <> 'CANCELADA' AND fecha_cancelacion IS NULL))
);

-- ---------------------------------------------------------------------
-- RESERVA_HABITACION: linea de la reserva = una habitacion con sus
-- propias fechas y numero de huespedes. 
-- ---------------------------------------------------------------------
CREATE TABLE reserva_habitacion (
  id_reserva_hab  NUMBER      GENERATED BY DEFAULT AS IDENTITY,
  id_reserva      NUMBER      NOT NULL,
  id_habitacion   NUMBER      NOT NULL,
  fecha_checkin   DATE        NOT NULL,
  fecha_checkout  DATE        NOT NULL,
  num_huespedes   NUMBER(2)   NOT NULL,
  CONSTRAINT pk_reserva_habitacion  PRIMARY KEY (id_reserva_hab),
  CONSTRAINT fk_reshab_reserva      FOREIGN KEY (id_reserva)
                                    REFERENCES reserva (id_reserva),
  CONSTRAINT fk_reshab_habitacion   FOREIGN KEY (id_habitacion)
                                    REFERENCES habitacion (id_habitacion),
  CONSTRAINT uq_reshab_res_hab      UNIQUE (id_reserva, id_habitacion),
  CONSTRAINT ck_reshab_fechas       CHECK (fecha_checkout > fecha_checkin),
  CONSTRAINT ck_reshab_huespedes    CHECK (num_huespedes > 0)
);

-- ---------------------------------------------------------------------
-- PAGO: abonos o pagos de una reserva (anticipo + saldo, etc.).
-- ---------------------------------------------------------------------
CREATE TABLE pago (
  id_pago     NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  id_reserva  NUMBER        NOT NULL,
  fecha_pago  DATE          DEFAULT SYSDATE NOT NULL,
  monto       NUMBER(12,2)  NOT NULL,
  metodo      VARCHAR2(20)  NOT NULL,
  estado      VARCHAR2(12)  DEFAULT 'PENDIENTE' NOT NULL,
  CONSTRAINT pk_pago         PRIMARY KEY (id_pago),
  CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva)
                             REFERENCES reserva (id_reserva),
  CONSTRAINT ck_pago_monto   CHECK (monto > 0),
  CONSTRAINT ck_pago_metodo  CHECK (metodo IN ('TARJETA_CREDITO','TARJETA_DEBITO',
                                               'PSE','TRANSFERENCIA','EFECTIVO')),
  CONSTRAINT ck_pago_estado  CHECK (estado IN ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO'))
);

-- ---------------------------------------------------------------------
-- RESERVA_SERVICIO: servicios contratados en una reserva y su cantidad.
-- ---------------------------------------------------------------------
CREATE TABLE reserva_servicio (
  id_reserva       NUMBER        NOT NULL,
  id_servicio      NUMBER        NOT NULL,
  cantidad         NUMBER(3)     NOT NULL,
  precio_unitario  NUMBER(12,2)  NOT NULL,
  CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva, id_servicio),
  CONSTRAINT fk_resserv_reserva  FOREIGN KEY (id_reserva)
                                 REFERENCES reserva (id_reserva),
  CONSTRAINT fk_resserv_servicio FOREIGN KEY (id_servicio)
                                 REFERENCES servicio (id_servicio),
  CONSTRAINT ck_resserv_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_resserv_precio   CHECK (precio_unitario >= 0)
);

-- ---------------------------------------------------------------------
-- RESENA: resena de una estadia. 
-- ---------------------------------------------------------------------
CREATE TABLE resena (
  id_resena     NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  id_reserva    NUMBER         NOT NULL,
  calificacion  NUMBER(1)      NOT NULL,
  comentario    VARCHAR2(500),
  fecha_resena  DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_resena         PRIMARY KEY (id_resena),
  CONSTRAINT fk_resena_reserva FOREIGN KEY (id_reserva)
                               REFERENCES reserva (id_reserva),
  CONSTRAINT uq_resena_reserva UNIQUE (id_reserva),
  CONSTRAINT ck_resena_calif   CHECK (calificacion BETWEEN 1 AND 5)
);

-- =====================================================================
-- 4. USUARIOS INTERNOS
-- =====================================================================
CREATE TABLE usuario_sistema (
  id_usuario      NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  id_rol          NUMBER         NOT NULL,
  id_alojamiento  NUMBER,
  nombre          VARCHAR2(120)  NOT NULL,
  correo          VARCHAR2(100)  NOT NULL,
  CONSTRAINT pk_usuario_sistema     PRIMARY KEY (id_usuario),
  CONSTRAINT fk_usuario_rol         FOREIGN KEY (id_rol)
                                    REFERENCES rol (id_rol),
  CONSTRAINT fk_usuario_alojamiento FOREIGN KEY (id_alojamiento)
                                    REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uq_usuario_correo      UNIQUE (correo),
  CONSTRAINT ck_usuario_correo      CHECK (correo LIKE '%_@_%._%')
);

-- =====================================================================
-- 5. COMENTARIOS EN EL DICCIONARIO DE DATOS 
-- =====================================================================
COMMENT ON TABLE municipio          IS 'Los 12 municipios del Quindio donde se ubican los alojamientos.';
COMMENT ON TABLE tipo_alojamiento   IS 'Catalogo de tipos de alojamiento: finca cafetera, hotel, glamping, hostal, otros.';
COMMENT ON TABLE rol                IS 'Catalogo de roles de los usuarios internos (administrador, encargado).';
COMMENT ON TABLE temporada          IS 'Periodos con rango de fechas y categoria alta/media/baja, definidos por anio.';
COMMENT ON TABLE cliente            IS 'Huespedes registrados en la plataforma; documento y correo unicos.';
COMMENT ON TABLE alojamiento        IS 'Establecimiento turistico de un municipio y un tipo; estrellas autoasignadas.';
COMMENT ON TABLE habitacion         IS 'Habitaciones de un alojamiento; numero unico dentro del alojamiento.';
COMMENT ON TABLE tarifa             IS 'Precio por noche de cada habitacion en cada temporada (habitacion x temporada).';
COMMENT ON TABLE servicio           IS 'Servicios complementarios, propios de cada alojamiento.';
COMMENT ON TABLE reserva            IS 'Cabecera de la reserva: cliente, alojamiento, rango general de fechas y estado.';
COMMENT ON TABLE reserva_habitacion IS 'Detalle de la reserva: cada habitacion reservada con sus propias fechas y huespedes.';
COMMENT ON TABLE pago               IS 'Pagos y abonos de una reserva, con metodo y estado.';
COMMENT ON TABLE reserva_servicio   IS 'Servicios contratados en una reserva, con cantidad y precio unitario vigente.';
COMMENT ON TABLE resena             IS 'Resena de una estadia completada: calificacion 1-5 y comentario opcional.';
COMMENT ON TABLE usuario_sistema    IS 'Usuarios internos: administradores y encargados de alojamiento, cada uno con un rol.';

-- Comentarios de columnas clave
COMMENT ON COLUMN alojamiento.estrellas          IS 'Calificacion autoasignada por el alojamiento (no proviene de resenas).';
COMMENT ON COLUMN temporada.anio                 IS 'Anio en que inicia la temporada.';
COMMENT ON COLUMN reserva.id_alojamiento         IS 'Redundancia controlada: alojamiento al que pertenecen las habitaciones y servicios.';
COMMENT ON COLUMN reserva.fecha_cancelacion      IS 'Obligatoria solo si estado = CANCELADA; base de la regla de reembolso (5 dias).';
COMMENT ON COLUMN reserva_servicio.precio_unitario IS 'Precio del servicio al momento de contratarlo.';


